import { expect, test } from '@playwright/test'

for (const width of [375, 1280, 1440, 1920]) {
  test(`remaining business dialogs trap and restore focus at ${width}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/api/**', route => route.abort())
    await page.goto('/tests/ui/fixtures/business-dialogs.html')
    for (const name of ['新建知识库', '上传文档', '重建索引', '添加订阅', 'AI 生成报告']) {
      const opener = page.getByRole('button', { name, exact: true })
      await opener.click()
      const dialog = page.getByRole('dialog', { name, exact: true })
      await expect(dialog).toBeVisible()
      const close = dialog.getByRole('button', { name: '关闭', exact: true })
      await close.focus()
      await page.keyboard.press('Shift+Tab')
      expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
      await page.keyboard.press('Tab')
      await expect(close).toBeFocused()
      await dialog.getByRole('heading', { name, exact: true }).click()
      await expect(dialog).toBeVisible()
      expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await expect(dialog).toHaveCSS('background-color', 'rgb(255, 255, 255)')
      await page.screenshot({ path: testInfo.outputPath(`${name}-${width}.png`) })
      await page.keyboard.press('Escape')
      await expect(dialog).toHaveCount(0)
      await expect(opener).toBeFocused()
      await opener.click()
      await dialog.getByRole('heading', { name, exact: true }).click()
      await page.mouse.click(2, 2)
      await expect(dialog).toHaveCount(0)
      await expect(opener).toBeFocused()
      await opener.click()
      await close.click()
      await expect(opener).toBeFocused()
    }
    expect(errors).toEqual([])
  })
}

test('subscription and report steps keep inputs and reset on close', async ({ page }) => {
  await page.route('**/api/**', route => route.abort())
  await page.goto('/tests/ui/fixtures/business-dialogs.html')
  await page.getByRole('button', { name: '添加订阅', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByRole('button').nth(1).click()
  await expect(dialog.getByText('配置订阅信息')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '添加订阅', exact: true }).click()
  await expect(page.getByText('选择数据源类型')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'AI 生成报告', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByRole('button').nth(1).click()
  const next = dialog.getByRole('button', { name: '下一步' })
  await expect(next).toBeDisabled()
  await dialog.getByPlaceholder('输入报告标题').fill('Dialog contract test')
  await next.click()
  await expect(dialog.getByText('Dialog contract test')).toBeVisible()
  await expect(dialog.getByText(/报告入库属于 L1 变更/)).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'AI 生成报告', exact: true }).click()
  await expect(page.getByText('选择报告类型')).toBeVisible()
})
