import { expect, test } from '@playwright/test'

for (const width of [390, 1280, 1440, 1920]) {
  test(`foundation geometry, pagination and dialog at ${width}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/tests/ui/fixtures/foundation.html')
    const standard = page.getByRole('button', { name: '标准按钮' })
    await expect(standard).toHaveCSS('height', '36px')
    await expect(standard).toHaveCSS('border-radius', '8px')
    await expect(page.getByRole('button', { name: '紧凑按钮' })).toHaveCSS('height', '32px')
    await expect(page.getByRole('heading', { level: 1 })).toHaveCSS('font-size', '24px')
    await expect(page.getByTestId('foundation-card')).toHaveCSS('border-radius', '12px')
    await expect(page.getByText('Card header', { exact: true })).toHaveCSS('font-size', '16px')
    await expect(page.getByRole('heading', { name: '未执行' })).toHaveCSS('font-size', '16px')
    const nav = page.getByRole('navigation', { name: '分页' })
    await expect(nav).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(nav).toHaveCSS('border-top-width', '0px')
    await page.getByRole('button', { name: '下一页' }).click()
    await expect(nav).toContainText('2 / 5')
    await page.getByLabel('每页条数').selectOption('50')
    await expect(page.getByLabel('每页条数')).toHaveValue('50')
    await page.getByLabel('跳转页码').fill('4')
    await page.getByLabel('跳转页码').press('Enter')
    await expect(nav).toContainText('4 / 5')
    const before = await standard.boundingBox()
    await page.getByRole('button', { name: '切换加载' }).click()
    expect(await standard.boundingBox()).toEqual(before)
    await expect(standard).toBeDisabled()
    await expect(page.getByRole('button', { name: '下一页' })).toBeDisabled()
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await expect(standard).toHaveCSS('transition-duration', '0s')
    await expect(standard.locator('svg')).toHaveCSS('animation-name', 'none')
    await page.getByText('技术详情', { exact: true }).click()
    await expect(page.getByText('reason_code=not_observed', { exact: true })).toBeVisible()
    const trigger = page.getByRole('button', { name: '打开对话框' })
    await trigger.click()
    const dialog = page.getByRole('dialog', { name: 'Foundation dialog' })
    await expect(dialog).toHaveAccessibleDescription('Dialog contract')
    await expect(dialog).toHaveCSS('border-radius', '12px')
    await expect(page.getByRole('button', { name: '首个操作' })).toBeFocused()
    for (let i = 0; i < 5; i++) {
      await page.keyboard.press('Tab')
      expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
    }
    const body = page.getByTestId('dialog-body')
    expect(await body.evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('foundation-dialog.png') })
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(trigger).toBeFocused()
    await trigger.click()
    await page.getByRole('button', { name: '关闭', exact: true }).click()
    await expect(trigger).toBeFocused()
    await page.screenshot({ path: testInfo.outputPath('foundation.png'), fullPage: true })
  })
}
