import { expect, test } from '@playwright/test'
import { envelope, runDetailRes } from './fixtures/runtime-detail'
test('Runtime skip link, semantic tab keyboard and form names', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('token', 'fixture'))
  await page.route('**/api/**', route => route.fulfill({ json: { data: { items: [], page: { total: 0 }, availability: 'available', data_quality: 'complete' } } }))
  await page.route('**/api/runtime/v1/runs/run-1', route => route.fulfill({ contentType: 'application/json', body: envelope(runDetailRes({ summary: { status: 'succeeded' } })) }))
  await page.goto('/runtime/runs/run-1')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: '跳到主要内容' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('main')).toBeFocused()
  const overview = page.getByRole('tab', { name: '概览' })
  await overview.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: '时间线' })).toBeFocused()
  await expect(page.getByRole('tabpanel')).toHaveAttribute('aria-labelledby', 'runtime-tab-timeline')
  await page.keyboard.press('End')
  await expect(page.getByRole('tab', { name: 'Trace', exact: true })).toBeFocused()
  await page.keyboard.press('Home')
  await expect(overview).toBeFocused()
  await page.getByRole('link', { name: '返回 Runs' }).click()
  await expect(page.getByRole('combobox', { name: '状态', exact: true })).toHaveAttribute('name')
  await expect(page.getByRole('textbox', { name: 'Session ID' })).toHaveAttribute('autocomplete', 'off')
  const color = await page.locator('main .text-gray-500').first().evaluate(el => getComputedStyle(el).color)
  expect(color).toBe('rgb(102, 112, 133)')
})
