-- +goose NO TRANSACTION
-- +goose Up
CREATE TABLE agent_approvals (
    id VARCHAR(128) NOT NULL,
    run_id VARCHAR(64) NOT NULL,
    tool_call_id_observed VARCHAR(128) NULL,
    tool_name VARCHAR(128) NOT NULL,
    tool_revision VARCHAR(128) NOT NULL,
    tool_schema_hash CHAR(64) NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    proposal_json_redacted JSON NOT NULL,
    proposal_hash CHAR(64) NOT NULL,
    policy_hash CHAR(64) NOT NULL,
    runtime_compatibility_hash CHAR(64) NOT NULL,
    requested_by VARCHAR(128) NOT NULL,
    decided_by VARCHAR(128) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'preparing',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    decision_reason TEXT NULL,
    interrupt_id VARCHAR(128) NULL,
    interrupt_address VARCHAR(512) NULL,
    checkpoint_id VARCHAR(128) NULL,
    checkpoint_payload_sha256 CHAR(64) NULL,
    checkpoint_lease_generation BIGINT UNSIGNED NULL,
    preparing_at DATETIME(3) NOT NULL,
    published_at DATETIME(3) NULL,
    expires_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    decided_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uidx_agent_approvals_run_proposal (run_id, proposal_hash),
    KEY idx_agent_approvals_status_expiry (status, expires_at, published_at),
    KEY idx_agent_approvals_run_status (run_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_effects (
    id VARCHAR(128) NOT NULL,
    run_id VARCHAR(64) NOT NULL,
    tool_call_id_observed VARCHAR(128) NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    effect_role VARCHAR(32) NOT NULL DEFAULT 'primary',
    effect_step VARCHAR(128) NOT NULL,
    parent_effect_id VARCHAR(128) NULL,
    proposal_hash CHAR(64) NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    tool_revision VARCHAR(128) NOT NULL,
    tool_schema_hash CHAR(64) NOT NULL,
    target_hash CHAR(64) NOT NULL,
    request_redacted JSON NULL,
    response_redacted JSON NULL,
    effect_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    external_reference VARCHAR(512) NULL,
    lease_generation BIGINT UNSIGNED NOT NULL,
    attempt INT UNSIGNED NOT NULL DEFAULT 0,
    reconciliation_attempts INT UNSIGNED NOT NULL DEFAULT 0,
    next_reconcile_at DATETIME(3) NULL,
    resolution VARCHAR(64) NULL,
    resolution_evidence_redacted JSON NULL,
    resolved_by VARCHAR(128) NULL,
    resolved_at DATETIME(3) NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    last_error TEXT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uidx_agent_effects_idempotency (idempotency_key),
    UNIQUE KEY uidx_agent_effects_proposal_step (run_id, proposal_hash, effect_step),
    KEY idx_agent_effects_reconcile (status, next_reconcile_at, effect_type),
    KEY idx_agent_effects_run_status (run_id, status, created_at),
    KEY idx_agent_effects_parent (parent_effect_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- +goose Down
DROP TABLE IF EXISTS agent_effects;
DROP TABLE IF EXISTS agent_approvals;
