FROM node:24.19.0-alpine AS builder
WORKDIR /app
COPY web/package.json web/package-lock.json ./
RUN npm ci
COPY web/ ./
RUN npm run build

FROM nginx:1.27-alpine@sha256:ec0dfb306e19c90315e231a8c61b896693593fe766c131f9be54bae820cd3f02
RUN rm -f /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
COPY manifest/docker/nginx/frontend.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT []
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 80
