FROM golang:1.27.0-bookworm AS builder

ARG GOOSE_VERSION=v3.27.3
RUN CGO_ENABLED=0 go install github.com/pressly/goose/v3/cmd/goose@${GOOSE_VERSION}

FROM debian:bookworm-slim

COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY migrations /migrations

ENTRYPOINT ["goose"]
