import { act, renderHook } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { useSSECursor } from '@/hooks/useSSECursor'
const response = (text: string) => new Response(new ReadableStream({ start(c) { c.enqueue(new TextEncoder().encode(text)); c.close() } }))
const visibility = async (state: 'hidden' | 'visible') => { await act(async () => { Object.defineProperty(document, 'visibilityState', { configurable: true, value: state }); document.dispatchEvent(new Event('visibilitychange')) }) }
beforeEach(() => { vi.useFakeTimers(); vi.stubGlobal('fetch', vi.fn()); Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'visible' }) })
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); vi.restoreAllMocks() })
it('owns one listener; pauses hidden retries and refreshes once immediately visible', async () => {
  const add = vi.spyOn(document, 'addEventListener'), remove = vi.spyOn(document, 'removeEventListener')
  vi.mocked(fetch).mockRejectedValueOnce(new TypeError('offline')).mockResolvedValue(response('id:1\nevent:run.completed\ndata:{}\n\n'))
  const { result, rerender, unmount } = renderHook(() => useSSECursor({ url: '/events', runId: 'r', onChunk: vi.fn() }))
  await act(async () => {}); rerender(); await visibility('hidden')
  await act(async () => { await vi.advanceTimersByTimeAsync(10000) })
  expect(fetch).toHaveBeenCalledOnce()
  await visibility('visible')
  expect(fetch).toHaveBeenCalledTimes(2)
  expect(result.current.done).toBe(true)
  await visibility('hidden'); await visibility('visible')
  expect(fetch).toHaveBeenCalledTimes(2)
  expect(add.mock.calls.filter(([event]) => event === 'visibilitychange')).toHaveLength(1)
  unmount()
  expect(remove.mock.calls.filter(([event]) => event === 'visibilitychange')).toHaveLength(1)
  expect(vi.getTimerCount()).toBe(0)
})
it('starts hidden without fetch and cancels retry on unmount', async () => {
  Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'hidden' })
  vi.mocked(fetch).mockRejectedValue(new TypeError('offline'))
  const { unmount } = renderHook(() => useSSECursor({ url: '/events', runId: 'r', onChunk: vi.fn() }))
  await act(async () => {})
  expect(fetch).not.toHaveBeenCalled()
  await visibility('visible')
  expect(fetch).toHaveBeenCalledOnce()
  unmount()
  await act(async () => { await vi.advanceTimersByTimeAsync(10000) })
  expect(fetch).toHaveBeenCalledOnce()
  expect(vi.getTimerCount()).toBe(0)
})
it('keeps content/cursor across error and manual retry, using latest callback', async () => {
  vi.mocked(fetch).mockResolvedValueOnce(response('id:1\nevent:message.delta\ndata:{"text":"kept"}\n\n')).mockResolvedValueOnce(response('id:1\nevent:message.delta\ndata:{"text":"kept"}\n\nid:2\nevent:run.completed\ndata:{}\n\n'))
  const chunks: string[] = []
  const { result, rerender } = renderHook(({ callback }) => useSSECursor({ url: '/events', runId: 'r', maxRetries: 0, onChunk: callback }), { initialProps: { callback: (_type: string, content: string) => { chunks.push(content) } } })
  await act(async () => {})
  expect(chunks).toEqual(['{"text":"kept"}'])
  expect(result.current.error?.code).toBe('retries_exhausted')
  expect(result.current.cursor.lastSeq).toBe(1)
  const latest = vi.fn(); rerender({ callback: latest })
  await act(async () => { result.current.retry() })
  expect(chunks).toEqual(['{"text":"kept"}'])
  expect(latest).toHaveBeenCalledOnce()
  expect(fetch).toHaveBeenLastCalledWith('/events?after_seq=1', expect.anything())
  expect(result.current.error).toBeNull()
  expect(result.current.done).toBe(true)
})

it('keeps a live tail while hidden and avoids duplicate requests on visibility changes', async () => {
  const cancel = vi.fn()
  vi.mocked(fetch).mockResolvedValue(new Response(new ReadableStream({ cancel })))
  const { unmount } = renderHook(() => useSSECursor({ url: '/events', runId: 'r', onChunk: vi.fn() }))
  await act(async () => {})
  await visibility('hidden'); await visibility('visible')
  expect(fetch).toHaveBeenCalledOnce()
  expect(cancel).not.toHaveBeenCalled()
  unmount()
  await act(async () => {})
  expect(cancel).toHaveBeenCalledOnce()
})

it('switches Run cursors without replaying old content or retaining old transport done state', async () => {
  vi.mocked(fetch).mockResolvedValueOnce(response('id:7\nevent:run.completed\ndata:{}\n\n')).mockResolvedValueOnce(response('id:1\nevent:run.completed\ndata:{}\n\n'))
  const { result, rerender } = renderHook(({ runId }) => useSSECursor({ url: '/events', runId, onChunk: vi.fn() }), { initialProps: { runId: 'a' } })
  await act(async () => {})
  expect(result.current.cursor.lastSeq).toBe(7)
  rerender({ runId: 'b' })
  await act(async () => {})
  expect(fetch).toHaveBeenLastCalledWith('/events?after_seq=0', expect.anything())
  expect(result.current.cursor.lastSeq).toBe(1)
})

it('replays an undelivered event on manual retry after the consumer throws', async () => {
  const event = 'id:1\nevent:message.delta\ndata:{"text":"deliver on retry"}\n\n'
  vi.mocked(fetch).mockResolvedValueOnce(response(event)).mockResolvedValueOnce(response(event + 'data:[DONE]\n\n'))
  const deliveries: string[] = []
  const consumer = vi.fn((_type: string, content: string) => {
    if (consumer.mock.calls.length === 1) throw new Error('consumer failed before recording content')
    deliveries.push(content)
  })
  const { result, unmount } = renderHook(() => useSSECursor({ url: '/events', runId: 'r', onChunk: consumer }))
  await act(async () => {})
  expect(result.current.error?.code).toBe('consumer')
  expect(result.current.cursor.lastSeq).toBe(0)
  expect(deliveries).toEqual([])
  expect(fetch).toHaveBeenCalledOnce()

  await act(async () => { result.current.retry() })
  expect(vi.mocked(fetch).mock.calls.map(([url]) => url)).toEqual(['/events?after_seq=0', '/events?after_seq=0'])
  expect(deliveries).toEqual(['{"text":"deliver on retry"}'])
  expect(consumer).toHaveBeenCalledTimes(2)
  expect(result.current.cursor.lastSeq).toBe(1)
  expect(result.current.error).toBeNull()
  expect(result.current.done).toBe(true)
  unmount()
})
